---

- name: add gitlab key
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    state: present

- name: add gitlab repo
  apt_repository:
    repo: "deb https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-runner
    state: present
    update_cache: yes

- name: add gitlab src-repo
  apt_repository:
    repo: "deb-src https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
    filename: gitlab-runner
    state: present
    update_cache: yes

- name: install packages
  apt:
    name: "{{item}}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoremove: yes
  with_items:
  - gitlab-runner

- name: register docker runner
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "{{ gitlab_external_url }}" \
    --registration-token "{{ gitlab_runner_token }}" \
    --description "{{ gitlab_runner_description }}" \
    --executor "docker" \
    --docker-tlsverify=false \
    --docker-privileged \
    --tag-list '{{ gitlab_runner_tags | join(",") }}' \
    --run-untagged=true \
    --docker-image='{{ gitlab_runner_image |default('alpine') }}' \
    --request-concurrency {{ gitlab_runner_concurrent }}
    --docker-volumes='/var/run/docker.sock:/var/run/docker.sock,/cache'

...
