---
version: '3.9'

services:

  gitlab:
    image: gitlab/gitlab-ee
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.runner.lokal'
    ports:
      - '80:80'
      - '2020:22'
    shm_size: '256m'

...
